version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: metro
    versions:
    - ">= 0"
  - dependency-name: metro-react-native-babel-preset
    versions:
    - ">= 0"
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: "@jonny/eslint-config"
    versions:
    - 2.1.221
  - dependency-name: "@react-navigation/core"
    versions:
    - 5.15.1
    - 5.15.2
